Name: sampledemo_$(Date:yyyyMMdd)$(Rev:r)
trigger:
  - Main
pool:
  # name: Default
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    inputs:
      version: '3.x'

  - task: MSBuild@1
    inputs:
      solution: '**/*.sln'
      msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'

# Name:trigger:
# - master

# pool:
#   vmImage: ubuntu-latest

# variables:
#   buildConfiguration: 'Release'

# steps:
# - script: dotnet build --configuration $(buildConfiguration)
#   displayName: 'dotnet build $(buildConfiguration)'