name: sampledemo_$(Date:yyyyMMdd)$(Rev:r)
trigger:
  - Main
pool:
  name: Default
steps:
  - task: UseDotNet@2
    inputs:
      version: '3.x'

  - task: MSBuild@1
    inputs:
      solution: '**/*.sln'
      msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
